function options = springs_default_options( )

options = struct( ...
	'precision' , 'double' , ...
	'algorithm' , 'newton' , ...
	'objective' , 'energy' , ...
	'num_iter_save' , 0 , ...
	'num_iter_print' , 0 , ...
	'num_iter_max' , 0 , ...
	'include_force_fixed_nodes' , false , ...
	'use_numerical_hessian' , false , ...
	'tolerance_change_objective' , 1.0e-12 , ...
	'tolerance_sum_net_force' , 1.0e-12 ) ;

end