function options = springs_default_options( )

options = struct( ...
	'precision' , 'double' , ...
	'algorithm' , 'newton' , ...
	'num_iter_save' , 0 , ...
	'num_iter_print' , 0 , ...
	'num_iter_max' , 0 , ...
	'tolerance_change_energy' , 1.0e-12 , ...
	'tolerance_sum_net_force' , 1.0e-12 ) ;

end