function display_3D( nodes , springs )

figure( ...
	'Position' , [0,0,1400,700] , ...
	'Color' , [1,1,1] )
axes( ...
	'XLim' , [ -1 34 ] , ...
	'YLim' , [ -1 34 ] , ...
	'ZLim' , [ -1 34 ] , ...
	'View' , [0,90],...%[ -25 , 25 ] , ...%
	'DataAspectRatio' , [1,1,1] , ...
	'NextPlot' , 'add' )
plot3( ...
	[ nodes.position( springs.nodes(:,1) ,1) , nodes.position( springs.nodes(:,2) ,1) ]' , ...
	[ nodes.position( springs.nodes(:,1) ,2) , nodes.position( springs.nodes(:,2) ,2) ]' , ...
	[ nodes.position( springs.nodes(:,1) ,3) , nodes.position( springs.nodes(:,2) ,3) ]' , ...
	'k-' , ...
	'LineWidth' , 1 )
% for pp = 1 : size(nodes.position,1)
% 	plot3( ...
% 		nodes.position(pp,1) + [0,nodes.force(pp,1)] , ...
% 		nodes.position(pp,2) + [0,nodes.force(pp,2)] , ...
% 		nodes.position(pp,3) + [0,nodes.force(pp,3)] , ...
% 		'r-' , ...
% 		'LineWidth' , 1 )
% end

end